packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  '@tanstack/react-query': ^5.90.5
  '@trpc/client': ^11.6.0
  '@trpc/server': ^11.6.0
  '@trpc/tanstack-react-query': ^11.6.0
  eslint: ^9.38.0
  prettier: ^3.6.2
  tailwindcss: ^3.4.18
  typescript: ^5.9.3
  zod: ^4.1.12

catalogs:
  react19:
    '@types/react': ^19.2.2
    '@types/react-dom': ^19.2.2
    react: ^19.0.0
    react-dom: ^19.1.1

linkWorkspacePackages: true

nodeLinker: hoisted

onlyBuiltDependencies:
  - esbuild

overrides:
  '@types/minimatch': 5.1.2
